# Generated by go2rpm 1.9.0
%bcond_without check

# https://github.com/patrickbr/gtfstidy
%global goipath         github.com/patrickbr/gtfstidy
Version:                0.2
%global commit          7c5f215bb0d17794e4ae4db9a07e222e31e7591c

# REMOVE BEFORE SUBMITTING THIS FOR REVIEW
# ---
# New Fedora packages should use %%gometa -f, which makes the package
# ExclusiveArch to %%golang_arches_future and thus excludes the package from
# %%ix86. If the new package is needed as a dependency for another package,
# please consider removing that package from %%ix86 in the same way, instead of
# building more go packages for i686. If your package is not a leaf package,
# you'll need to coordinate the removal of the package's dependents first.
# ---
# REMOVE BEFORE SUBMITTING THIS FOR REVIEW
# %gometa -f


%global common_description %{expand:
A tool for checking, sanitizing and minimizing GTFS feeds.}

%global golicenses      LICENSE
%global godocs          README.md processors/testfeed-err/agency.txt\\\
                        processors/testfeed-err/calendar.txt\\\
                        processors/testfeed-err/calendar_dates.txt\\\
                        processors/testfeed-err/fare_attributes.txt\\\
                        processors/testfeed-err/fare_rules.txt\\\
                        processors/testfeed-err/frequencies.txt\\\
                        processors/testfeed-err/levels.txt\\\
                        processors/testfeed-err/pathways.txt\\\
                        processors/testfeed-err/routes.txt\\\
                        processors/testfeed-err/shapes.txt\\\
                        processors/testfeed-err/stop_times.txt\\\
                        processors/testfeed-err/stops.txt\\\
                        processors/testfeed-err/trips.txt\\\
                        processors/testfeed-merge/agency.txt\\\
                        processors/testfeed-merge/calendar.txt\\\
                        processors/testfeed-merge/calendar_dates.txt\\\
                        processors/testfeed-merge/fare_attributes.txt\\\
                        processors/testfeed-merge/fare_rules.txt\\\
                        processors/testfeed-merge/frequencies.txt\\\
                        processors/testfeed-merge/levels.txt\\\
                        processors/testfeed-merge/pathways.txt\\\
                        processors/testfeed-merge/routes.txt\\\
                        processors/testfeed-merge/shapes.txt\\\
                        processors/testfeed-merge/stop_times.txt\\\
                        processors/testfeed-merge/stops.txt\\\
                        processors/testfeed-merge/trips.txt\\\
                        processors/testfeed/agency.txt\\\
                        processors/testfeed/attributions.txt\\\
                        processors/testfeed/calendar.txt\\\
                        processors/testfeed/calendar_dates.txt\\\
                        processors/testfeed/fare_attributes.txt\\\
                        processors/testfeed/fare_rules.txt\\\
                        processors/testfeed/frequencies.txt\\\
                        processors/testfeed/levels.txt\\\
                        processors/testfeed/pathways.txt\\\
                        processors/testfeed/routes.txt\\\
                        processors/testfeed/shapes.txt\\\
                        processors/testfeed/stop_times.txt\\\
                        processors/testfeed/stops.txt\\\
                        processors/testfeed/trips.txt

Name:           %{goname}
Release:        %autorelease
Summary:        A tool for checking, sanitizing and minimizing GTFS feeds

License:        AGPL-1.0-only
URL:            %{gourl}
Source:         %{gosource}

%description %{common_description}

%gopkg

%prep
%goprep
%autopatch -p1

%generate_buildrequires
%go_generate_buildrequires

%build
%gobuild -o %{gobuilddir}/bin/gtfstidy %{goipath}

%install
%gopkginstall
install -m 0755 -vd                     %{buildroot}%{_bindir}
install -m 0755 -vp %{gobuilddir}/bin/* %{buildroot}%{_bindir}/

%if %{with check}
%check
%gocheck
%endif

%files
%license LICENSE
%doc README.md processors/testfeed-err/agency.txt
%doc processors/testfeed-err/calendar.txt
%doc processors/testfeed-err/calendar_dates.txt
%doc processors/testfeed-err/fare_attributes.txt
%doc processors/testfeed-err/fare_rules.txt
%doc processors/testfeed-err/frequencies.txt processors/testfeed-err/levels.txt
%doc processors/testfeed-err/pathways.txt processors/testfeed-err/routes.txt
%doc processors/testfeed-err/shapes.txt processors/testfeed-err/stop_times.txt
%doc processors/testfeed-err/stops.txt processors/testfeed-err/trips.txt
%doc processors/testfeed-merge/agency.txt processors/testfeed-merge/calendar.txt
%doc processors/testfeed-merge/calendar_dates.txt
%doc processors/testfeed-merge/fare_attributes.txt
%doc processors/testfeed-merge/fare_rules.txt
%doc processors/testfeed-merge/frequencies.txt
%doc processors/testfeed-merge/levels.txt processors/testfeed-merge/pathways.txt
%doc processors/testfeed-merge/routes.txt processors/testfeed-merge/shapes.txt
%doc processors/testfeed-merge/stop_times.txt
%doc processors/testfeed-merge/stops.txt processors/testfeed-merge/trips.txt
%doc processors/testfeed/agency.txt processors/testfeed/attributions.txt
%doc processors/testfeed/calendar.txt processors/testfeed/calendar_dates.txt
%doc processors/testfeed/fare_attributes.txt processors/testfeed/fare_rules.txt
%doc processors/testfeed/frequencies.txt processors/testfeed/levels.txt
%doc processors/testfeed/pathways.txt processors/testfeed/routes.txt
%doc processors/testfeed/shapes.txt processors/testfeed/stop_times.txt
%doc processors/testfeed/stops.txt processors/testfeed/trips.txt
%{_bindir}/*

%gopkgfiles

%changelog
%autochangelog
